package packet

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"html"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/fall-out-bug/portolan/internal/graph"
)

type Options struct {
	GraphPath  string
	OutputPath string
	Force      bool
}

func Run(opts Options) ([]byte, error) {
	if opts.GraphPath == "" {
		return nil, errors.New("--graph is required")
	}
	if opts.OutputPath == "" {
		return nil, errors.New("--out is required")
	}

	g, err := LoadGraph(opts.GraphPath)
	if err != nil {
		return nil, err
	}
	return RenderMarkdown(g), nil
}

func LoadGraph(path string) (graph.Graph, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return graph.Graph{}, fmt.Errorf("read graph: %w", err)
	}
	var g graph.Graph
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&g); err != nil {
		return graph.Graph{}, fmt.Errorf("parse graph: %w", err)
	}
	if decoder.Decode(&struct{}{}) != io.EOF {
		return graph.Graph{}, fmt.Errorf("parse graph: trailing JSON content")
	}
	if g.SchemaVersion != graph.SchemaVersion {
		return graph.Graph{}, fmt.Errorf("graph schema_version must be %q", graph.SchemaVersion)
	}
	if g.GeneratedBy == "" {
		return graph.Graph{}, fmt.Errorf("graph generated_by is required")
	}
	for _, node := range g.Nodes {
		if node.ID == "" || node.Kind == "" || node.Label == "" {
			return graph.Graph{}, fmt.Errorf("graph node %q is incomplete", node.ID)
		}
		if err := validateEvidence("node "+node.ID, node.Evidence); err != nil {
			return graph.Graph{}, err
		}
	}
	for _, edge := range g.Edges {
		if edge.From == "" || edge.To == "" || edge.Kind == "" {
			return graph.Graph{}, fmt.Errorf("graph edge %q->%q is incomplete", edge.From, edge.To)
		}
		if err := validateEvidence("edge "+edge.From+"->"+edge.To, edge.Evidence); err != nil {
			return graph.Graph{}, err
		}
	}
	return g, nil
}

func RenderMarkdown(g graph.Graph) []byte {
	var b strings.Builder
	stateCounts := evidenceStateCounts(g)

	b.WriteString("# Portolan Evidence Packet\n\n")
	fmt.Fprintf(&b, "- Schema version: `%s`\n", g.SchemaVersion)
	fmt.Fprintf(&b, "- Generated by: `%s`\n", g.GeneratedBy)
	fmt.Fprintf(&b, "- Nodes: %d\n", len(g.Nodes))
	fmt.Fprintf(&b, "- Edges: %d\n\n", len(g.Edges))

	b.WriteString("## Evidence State Summary\n\n")
	for _, state := range orderedStates(stateCounts) {
		fmt.Fprintf(&b, "- `%s`: %d\n", state, stateCounts[state])
	}
	if len(stateCounts) == 0 {
		b.WriteString("- No evidence facts.\n")
	}
	b.WriteString("\n")

	writeNodeSection(&b, "## Visible Source Facts", g.Nodes, graph.SourceVisible, "visible source evidence")
	writeNodeSection(&b, "## Metadata-Visible Facts", g.Nodes, graph.MetadataVisible, "metadata-visible evidence")
	writeNodeSection(&b, "## Runtime-Visible Facts", g.Nodes, graph.RuntimeVisible, "runtime-visible evidence")
	writeNodeSection(&b, "## Claim-Only Facts", g.Nodes, graph.ClaimOnly, "claimed, not observed")
	writeNodeSection(&b, "## Unknown Areas", g.Nodes, graph.Unknown, "unknown")
	writeNodeSection(&b, "## Cannot Verify Areas", g.Nodes, graph.CannotVerify, "cannot verify")
	writeEdgeSection(&b, g.Edges)

	return []byte(b.String())
}

func Write(path string, data []byte, force bool) error {
	if err := validateOutputPath(path, force); err != nil {
		return err
	}
	parent := filepath.Dir(path)
	temp, err := os.CreateTemp(parent, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("create temporary packet: %w", err)
	}
	tempPath := temp.Name()
	defer os.Remove(tempPath)

	if _, err := temp.Write(data); err != nil {
		temp.Close()
		return fmt.Errorf("write packet: %w", err)
	}
	if err := temp.Close(); err != nil {
		return fmt.Errorf("write packet: %w", err)
	}
	if err := os.Rename(tempPath, path); err != nil {
		return fmt.Errorf("replace packet: %w", err)
	}
	return nil
}

func validateEvidence(label string, evidence graph.Evidence) error {
	if evidence.Source == "" {
		return fmt.Errorf("%s evidence source is required", label)
	}
	switch evidence.State {
	case graph.SourceVisible, graph.MetadataVisible, graph.RuntimeVisible, graph.ClaimOnly, graph.Unknown, graph.CannotVerify:
		return nil
	default:
		return fmt.Errorf("%s evidence state %q is not supported", label, evidence.State)
	}
}

func validateOutputPath(path string, force bool) error {
	if path == "" {
		return errors.New("--out is required")
	}
	parent := filepath.Dir(path)
	info, err := os.Stat(parent)
	if err != nil {
		return fmt.Errorf("output parent must exist: %w", err)
	}
	if !info.IsDir() {
		return fmt.Errorf("output parent is not a directory")
	}
	if info, err := os.Lstat(path); err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("output path must not be a symlink")
		}
		if info.IsDir() {
			return fmt.Errorf("output path must not be a directory")
		}
		if !force {
			return fmt.Errorf("output path already exists; use --force to overwrite")
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("inspect output path: %w", err)
	}
	return nil
}

func evidenceStateCounts(g graph.Graph) map[graph.EvidenceState]int {
	counts := map[graph.EvidenceState]int{}
	for _, node := range g.Nodes {
		counts[node.Evidence.State]++
	}
	for _, edge := range g.Edges {
		counts[edge.Evidence.State]++
	}
	return counts
}

func orderedStates(counts map[graph.EvidenceState]int) []graph.EvidenceState {
	states := make([]graph.EvidenceState, 0, len(counts))
	for state := range counts {
		states = append(states, state)
	}
	sort.Slice(states, func(i, j int) bool {
		return states[i] < states[j]
	})
	return states
}

func writeNodeSection(b *strings.Builder, title string, nodes []graph.Node, state graph.EvidenceState, label string) {
	b.WriteString(title + "\n\n")
	wrote := false
	for _, node := range nodes {
		if node.Evidence.State != state {
			continue
		}
		wrote = true
		fmt.Fprintf(b, "- `%s` (%s, id `%s`) is %s from `%s`", codeText(node.Label), codeText(node.Kind), codeText(node.ID), label, codeText(node.Evidence.Source))
		if node.Evidence.Reason != "" {
			fmt.Fprintf(b, ": %s", markdownText(node.Evidence.Reason))
		}
		b.WriteString(".\n")
	}
	if !wrote {
		b.WriteString("- None.\n")
	}
	b.WriteString("\n")
}

func writeEdgeSection(b *strings.Builder, edges []graph.Edge) {
	b.WriteString("## Relationships\n\n")
	if len(edges) == 0 {
		b.WriteString("- None.\n\n")
		return
	}
	for _, edge := range edges {
		description := evidenceDescription(edge.Evidence.State)
		fmt.Fprintf(b, "- `%s` `%s` `%s` is %s from `%s`", codeText(edge.From), codeText(edge.Kind), codeText(edge.To), description, codeText(edge.Evidence.Source))
		if edge.Evidence.Reason != "" {
			fmt.Fprintf(b, ": %s", markdownText(edge.Evidence.Reason))
		}
		b.WriteString(".\n")
	}
	b.WriteString("\n")
}

func codeText(value string) string {
	value = strings.ReplaceAll(value, "`", "'")
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	return html.EscapeString(value)
}

func markdownText(value string) string {
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	return html.EscapeString(value)
}

func evidenceDescription(state graph.EvidenceState) string {
	switch state {
	case graph.SourceVisible:
		return "visible source evidence"
	case graph.MetadataVisible:
		return "metadata-visible evidence"
	case graph.RuntimeVisible:
		return "runtime-visible evidence"
	case graph.ClaimOnly:
		return "claimed, not observed"
	case graph.Unknown:
		return "unknown"
	case graph.CannotVerify:
		return "cannot verify"
	default:
		return string(state)
	}
}
