/**
 * Domain: reading model for the atlas navigation surface (captain-atlas 15).
 *
 * Single responsibility: turn the parsed nav-atlas artifact set into READING
 * objects — named system journeys, route diagrams, route theses, stage roles,
 * anchor status, coverage regions, top probes, and agent-handoff queries — that
 * the shell renders as a walkthrough-first reading experience.
 *
 * Why this is fixture/profile-authored, not a generic template: the
 * charter-08 + doc-15 product bar is "understand the system", not "restate
 * route_family/stage counts". A purely mechanical template (e.g.
 *   title = journeyLabel(route_family); body = `${stages} stages across
 *   ${subjects}`)
 * regresses to exactly the JSONL-field-dump the spec calls a failure. So this
 * module carries HONEST, profile-authored narrative content: Bigtop is taught
 * as a BOM->recipe->provisioner->smoke->runtime distribution whose confidence
 * stops at static source. The narratives are GENERATED by these functions from
 * the real artifact set (stage roles, evidence states, runtime assessments,
 * attached finding/probe ids, coverage subjects) — they are not hand-written
 * into final HTML — and they degrade honestly when the underlying artifacts are
 * sparse or absent.
 *
 * PURE: no DOM, no I/O, no fs. Domain layer — zero dependencies. Anchor-status
 * classification here works off fields already present on the parsed nav-atlas;
 * the richer snippet/anchor resolution happens export-time in the adapter and is
 * threaded back in via enriched in-memory rows (source_excerpt / anchor_status).
 */
'use strict';

// ---------------------------------------------------------------------------
// Journey catalogue — profile-authored narrative, keyed by route_id.
// ---------------------------------------------------------------------------
// Each entry teaches the SYSTEM meaning of its route: what the journey is, why
// it matters, where confidence stops, and what an agent should do next. These
// strings are product copy, not JSONL field restatements. They are referenced by
// buildJourneys() which attaches the REAL derived facts (subjects, findings,
// probes, evidence states, coverage) so the rendered card answers the six
// questions without the admiral reading raw artifacts.
//
// `journeyId` is stable for harness/DOM markers; `readingPriority` orders the
// first screen. Only journeys whose route_id actually exists in the parsed
// nav-atlas are emitted, so a bundle never advertises a journey it cannot back.
const ROUTE_JOURNEYS = {
  'route:bigtop:package-distribution': {
    journeyId: 'journey:bigtop:package-to-runtime',
    title: 'Package Definition To Runtime Candidate',
    journeySummary:
      'Bigtop is a distribution: it declares component versions in a Bill of Materials, ' +
      'maps each into a per-component package recipe, and points deployment and provisioning ' +
      '(Puppet/Docker) at the artifacts those recipes produce. A smoke and interoperability ' +
      'test surface is supposed to close the loop before runtime.',
    whyItMatters:
      'This is the spine of Bigtop. If you want to know whether a given component is ' +
      'actually shippable, every link in this chain has to hold — and Portolan can only see ' +
      'the static chain, not whether it builds or runs.',
    whereConfidenceStops:
      'The BOM and recipe anchors are source-visible, but package build, provisioning, smoke, ' +
      'and runtime layout are all blocked or not assessed. Source visibility is not a working ' +
      'distribution.',
    readingPriority: 1,
  },
  'route:self:command-dispatch': {
    journeyId: 'journey:self:command-dispatch',
    title: 'Command Dispatch Entry Path',
    journeySummary:
      'The legacy Go CLI is a thin entrypoint: main delegates to a subcommand dispatch table ' +
      'in the app package, which fans out to internal handlers. This is how every portolan ' +
      'command currently begins.',
    whyItMatters:
      'The Go CLI overlaps the newer clean-stack JavaScript core on system-map concerns. ' +
      'Understanding where dispatch lives is the first step in seeing the legacy/current ' +
      'overlap and the version-skew risk it creates.',
    whereConfidenceStops:
      'The dispatch table is source-visible, but no build or runtime probe ran, so the ' +
      'command path is structurally mapped, not exercised.',
    readingPriority: 1,
  },
  'route:self:harness-script-workflow': {
    journeyId: 'journey:self:harness-script-workflow',
    title: 'Harness And Bundle Generation Workflow',
    journeySummary:
      'Acceptance is driven by shell harness scripts that wrap the JavaScript system-map ' +
      'builder, and by the /portolan:map entry point that loads intake, builds the snapshot, ' +
      'and exports the atlas. This is the workflow path an agent and a harness both walk.',
    whyItMatters:
      'This is the reproducibility spine: the generator, the validator, and the export path ' +
      'are all reached through these scripts, not ad hoc commands.',
    whereConfidenceStops:
      'The script and entry-point anchors are source-visible, but test suites and browser ' +
      'rendering of the exported atlas are blocked or not assessed.',
    readingPriority: 2,
  },
  'route:self:schema-validation': {
    journeyId: 'journey:self:schema-validation',
    title: 'Schema And Validator Duplication Boundary',
    journeySummary:
      'The frozen system-map schema is enforced by TWO semantic validators — one in the ' +
      'clean-stack core, one in the frozen viewer — across three regions. The route visits ' +
      'the schema and both validators to make the duplication legible.',
    whyItMatters:
      'Duplicate validators are a drift risk: a rule fixed in one stack can silently diverge ' +
      'in the other. This is the single clearest structural risk in portolan-self.',
    whereConfidenceStops:
      'Both validators are source-visible, but their behavior has not been diffed against the ' +
      'same fixture — that is a blocked test probe, not a verified fact.',
    readingPriority: 2,
  },
  'route:self:viewer-source-snippet': {
    journeyId: 'journey:self:viewer-source-snippet',
    title: 'Viewer Source-Preview Security Boundary',
    journeySummary:
      'The viewer serves source previews over HTTP. The route traces the server routing into ' +
      'a fail-closed realpath/path-traversal guard that must run before any file is read. The ' +
      'boundary is what keeps preview from becoming arbitrary file access.',
    whyItMatters:
      'A source-preview endpoint is a security-relevant surface. The route makes the guard ' +
      'visible and attaches the runtime probe that would actually exercise it.',
    whereConfidenceStops:
      'The guard is source-visible, but no traversal payload has been run against it — ' +
      'browser/runtime assessment is not done.',
    readingPriority: 3,
  },
};

// Route thesis copy — the "what this route explains" line at the top of the
// dossier. Teaches intent, not stage enumeration.
const ROUTE_THESES = {
  'route:bigtop:package-distribution':
    'How a Bigtop component travels from a declared version in the BOM to a candidate runtime ' +
    'artifact — and exactly where static, source-visible evidence runs out.',
  'route:self:command-dispatch':
    'How a portolan command enters the legacy Go CLI and reaches a subcommand handler.',
  'route:self:harness-script-workflow':
    'How acceptance and bundle generation are driven by harness scripts and the /portolan:map ' +
    'entry point.',
  'route:self:schema-validation':
    'Where the system-map schema is enforced, and why it is enforced in two places at once.',
  'route:self:viewer-source-snippet':
    'How a source-preview request reaches the fail-closed boundary that prevents path ' +
    'traversal.',
};

// Human-readable role labels for path_role, so a stage card says "Bill of
// Materials declaration" instead of "bom". Sourced from the doc-13 vocabulary;
// unknown roles fall back honestly.
const PATH_ROLE_LABELS = {
  entrypoint: 'Entry point',
  command_dispatch: 'Command dispatch',
  workflow_script: 'Workflow script',
  bundle_builder: 'Bundle / export builder',
  schema: 'Schema',
  validator: 'Validator',
  viewer_api: 'Viewer API surface',
  source_snippet_boundary: 'Source-preview security boundary',
  bom: 'Bill of Materials declaration',
  package_recipe: 'Package recipe',
  package_spec: 'Package specification',
  install_script: 'Install script',
  deploy_module: 'Deployment module',
  provisioner: 'Provisioner (Puppet / Docker)',
  smoke_test: 'Smoke / interoperability test',
  runtime_layout: 'Runtime layout',
  upstream_source: 'Upstream source',
  docs: 'Documentation',
  patch: 'Patch',
  fixture: 'Fixture',
  generated: 'Generated artifact',
  unknown: 'Unknown role',
};

// Evidence-state -> plain-language rendering (source visibility, not runtime
// proof). Used so the dossier never implies runtime verification.
const EVIDENCE_STATE_LABELS = {
  'source-visible': 'Source-visible',
  'metadata-visible': 'Metadata-visible',
  'runtime-visible': 'Runtime-visible',
  'claim-only': 'Claim only (no source seen)',
  unknown: 'Unknown',
  cannot_verify: 'Cannot verify',
  not_assessed: 'Not assessed',
  blocked: 'Blocked',
  failed: 'Failed',
};

// ---------------------------------------------------------------------------
// Journeys
// ---------------------------------------------------------------------------

/**
 * Build the system-journey list for a parsed nav-atlas.
 *
 * Emits, in priority order:
 *  - one journey per known ROUTE_JOURNEYS entry whose route_id is present;
 *  - a synthesized "Build And Smoke Confidence Boundary" journey when there are
 *    not_assessed/blocked runtime stages (the "where does confidence stop"
 *    journey the spec requires);
 *  - a synthesized "Repository Fleet Coverage" journey summarizing coverage
 *    scale (covered vs route-less subjects).
 *
 * Each journey object carries enough derived fact for the card to answer the
 * six required questions (what/why/involved/known/not-assessed/next) WITHOUT the
 * shell re-reading raw artifacts.
 *
 * @param {object} navAtlas parsed artifact set
 * @returns {Array<object>} journeys sorted by readingPriority
 */
function buildJourneys(navAtlas) {
  const ni = (navAtlas && navAtlas.navigationIndex) || [];
  const cm = (navAtlas && navAtlas.coverageMatrix) || [];
  const fi = (navAtlas && navAtlas.findings) || [];
  const up = (navAtlas && navAtlas.unknownProbes) || [];

  const routesById = indexRoutes(ni);
  const findingsById = new Map(fi.map(f => [f.finding_id, f]));
  const probesById = new Map(up.map(p => [p.unknown_id, p]));
  const out = [];

  for (const [routeId, meta] of Object.entries(ROUTE_JOURNEYS)) {
    const route = routesById.get(routeId);
    if (!route) continue; // never advertise a journey the bundle cannot back
    out.push(buildRouteJourney(route, meta, findingsById, probesById));
  }

  // Confidence-boundary journey (required by doc 15): surfaces every
  // not_assessed/blocked runtime stage as "this is where confidence stops".
  const confJourney = buildConfidenceBoundaryJourney(ni, up);
  if (confJourney) out.push(confJourney);

  // Fleet-coverage journey (required by doc 15): the "this is a fleet, not one
  // route" view, derived from the coverage matrix.
  const covJourney = buildFleetCoverageJourney(cm);
  if (covJourney) out.push(covJourney);

  out.sort((a, b) => (a.readingPriority || 99) - (b.readingPriority || 99));
  return out;
}

function indexRoutes(ni) {
  const map = new Map();
  for (const s of ni) {
    if (!map.has(s.route_id)) {
      map.set(s.route_id, {
        route_id: s.route_id,
        route_family: s.route_family,
        route_title: s.route_title,
        route_quality: s.route_quality,
        route_quality_note: s.route_quality_note || '',
        next_raw_check: '',
        stages: [],
        findingIds: new Set(),
        probeIds: new Set(),
        evidenceIds: new Set(),
        subjects: new Set(),
        sourceStates: new Set(),
        runtimeAssessments: new Set(),
      });
    }
    const r = map.get(s.route_id);
    r.stages.push(s);
    for (const f of s.finding_refs || []) r.findingIds.add(f);
    for (const p of s.unknown_probe_refs || []) r.probeIds.add(p);
    for (const e of s.evidence_refs || []) r.evidenceIds.add(e);
    if (s.subject_id) r.subjects.add(s.subject_id);
    if (s.source_evidence_state) r.sourceStates.add(s.source_evidence_state);
    if (s.runtime_assessment) r.runtimeAssessments.add(s.runtime_assessment);
    if (s.next_raw_check) r.next_raw_check = s.next_raw_check;
  }
  for (const r of map.values()) {
    r.stages.sort((a, b) => a.stage_index - b.stage_index);
    // route_quality is cumulatively degraded across stages; the last stage
    // carries the final value (matches nav-atlas-viewmodel + open-navigation-route).
    if (r.stages.length) {
      r.route_quality = r.stages[r.stages.length - 1].route_quality;
      r.route_quality_note = r.stages[r.stages.length - 1].route_quality_note || '';
    }
  }
  return map;
}

function buildRouteJourney(route, meta, findingsById, probesById) {
  const notAssessedRuntime = route.runtimeAssessments.has('not_assessed') || route.runtimeAssessments.has('blocked');
  const knownBits = [...route.sourceStates].sort().map(s => EVIDENCE_STATE_LABELS[s] || s);
  const findingRows = [...route.findingIds].map(id => findingsById.get(id)).filter(Boolean);
  const probeRows = [...route.probeIds].map(id => probesById.get(id)).filter(Boolean);

  // "Next expedition" for this journey: prefer the route's own next_raw_check,
  // fall back to the first probe's next_probe, then to the journey's
  // whereConfidenceStops note. Never empty.
  let nextStep = route.next_raw_check;
  if (!nextStep && probeRows.length) nextStep = probeRows[0].next_probe;
  if (!nextStep) nextStep = meta.whereConfidenceStops;

  return {
    journeyId: meta.journeyId,
    kind: 'route',
    routeId: route.route_id,
    title: meta.title,
    journeySummary: meta.journeySummary,
    whyItMatters: meta.whyItMatters,
    whereConfidenceStops: meta.whereConfidenceStops,
    known: knownBits.length ? knownBits.join(', ') : 'No source-visible stages recorded.',
    notAssessed: notAssessedRuntime
      ? 'Runtime/build/test stages are blocked or not assessed — do not read source visibility as a working system.'
      : 'No blocked runtime stages recorded for this journey.',
    involvedSubjects: [...route.subjects],
    involvedStageCount: route.stages.length,
    findingIds: [...route.findingIds],
    probeIds: [...route.probeIds],
    topFindingTitles: findingRows.slice(0, 2).map(f => f.title),
    topProbeSurfaces: probeRows.slice(0, 3).map(p => p.blocked_surface),
    nextStep,
    readingPriority: meta.readingPriority || 50,
    // honest label: this narrative is fixture/profile-authored, generated from
    // the artifact set, not hand-written into HTML and not claimed as live
    // extraction.
    provenance: 'fixture_backed',
  };
}

function buildConfidenceBoundaryJourney(ni, up) {
  // Collect runtime-not-assessed/blocked stages across all routes.
  const stopStages = ni.filter(s => s.runtime_assessment === 'not_assessed' || s.runtime_assessment === 'blocked');
  if (!stopStages.length) return null;
  const probesById = new Map(up.map(p => [p.unknown_id, p]));
  const probeIds = new Set();
  const routeIds = new Set();
  for (const s of stopStages) {
    for (const p of s.unknown_probe_refs || []) probeIds.add(p);
    routeIds.add(s.route_id);
  }
  const probeRows = [...probeIds].map(id => probesById.get(id)).filter(Boolean);
  return {
    journeyId: 'journey:confidence-boundary',
    kind: 'confidence_boundary',
    routeId: null,
    title: 'Build And Smoke Confidence Boundary',
    journeySummary:
      'Across every mapped route, Portolan can see the static source chain but cannot confirm ' +
      'that anything builds, provisions, passes smoke, or runs. This journey collects every ' +
      'stage where confidence stops, so the boundary is visible in one place rather than ' +
      'scattered across dossiers.',
    whyItMatters:
      'Source-visible is not verified. If you treat the atlas as proof the system works, you ' +
      'are reading past the boundary this journey draws.',
    whereConfidenceStops:
      'Every runtime/build/test stage here is blocked or not assessed. No probe ran in this ' +
      'expedition, so none of these stages can be called verified.',
    known: stopStages.length + ' stage(s) are source-visible or metadata-visible but runtime-unverified.',
    notAssessed:
      'Package build, provisioning, smoke tests, and runtime layout remain blocked or not ' +
      'assessed. This cannot be called verified without running probes.',
    involvedSubjects: [...new Set(stopStages.map(s => s.subject_id).filter(Boolean))],
    involvedStageCount: stopStages.length,
    findingIds: [],
    probeIds: [...probeIds],
    topFindingTitles: [],
    topProbeSurfaces: probeRows.slice(0, 4).map(p => p.blocked_surface),
    nextStep: probeRows.length
      ? probeRows[0].next_probe
      : 'Run one build or smoke probe in an approved sandbox to move a stage from not-assessed to verified.',
    readingPriority: 10,
    provenance: 'fixture_backed',
  };
}

function buildFleetCoverageJourney(cm) {
  if (!cm.length) return null;
  const regions = coverageRegions(cm);
  return {
    journeyId: 'journey:fleet-coverage',
    kind: 'fleet_coverage',
    routeId: null,
    title: 'Repository Fleet Coverage',
    journeySummary:
      'This landscape is a fleet, not one route. Coverage shows which subjects carry a real ' +
      'route, which are only partially mapped, and which sit outside any route at all.',
    whyItMatters:
      'A route-rich subject is understood; a route-less subject is a known unknown. The fleet ' +
      'view keeps the unmapped majority from being hidden by the one mapped route.',
    whereConfidenceStops:
      'Coverage records representation, not runtime proof. A "covered" subject has a route; it ' +
      'does not have a verified build or runtime.',
    known:
      regions.counts.total + ' subject(s): ' + regions.counts.covered + ' fully covered, ' +
      regions.counts.partial + ' partial, ' + regions.counts.routeless + ' route-less ' +
      '(route coverage partitions the fleet); separately, ' + regions.counts.missing +
      ' subject(s) have a missing/not-assessed promotion state.',
    notAssessed:
      regions.counts.routeless + regions.counts.missing > 0
        ? 'A portion of the fleet has no meaningful route — these are visible gaps, not hidden ones.'
        : 'No route-less or missing subjects recorded.',
    involvedSubjects: [],
    involvedStageCount: 0,
    findingIds: [],
    probeIds: [],
    topFindingTitles: [],
    topProbeSurfaces: [],
    nextStep: 'Open Coverage to drill from a region into its route, findings, or unknown probes.',
    readingPriority: 20,
    provenance: 'fixture_backed',
  };
}

// ---------------------------------------------------------------------------
// Route diagrams + thesis + stage role + anchor status
// ---------------------------------------------------------------------------

/**
 * Build a linear route diagram (ordered stages -> nodes, sequential flow -> edges)
 * from a route's stages. No graph library; the shell renders nodes/edges as a
 * wrapped flex flow with arrows. Each node carries role/evidence/runtime/finding
 * /probe signals so the diagram is legible without a table.
 *
 * @param {Array<object>} stages ordered navigation-index stage rows for one route
 * @returns {{nodes:Array, edges:Array}}
 */
function buildRouteDiagram(stages) {
  const sorted = [...stages].sort((a, b) => a.stage_index - b.stage_index);
  const nodes = sorted.map(s => ({
    stageIndex: s.stage_index,
    label: stageLabel(s),
    role: PATH_ROLE_LABELS[s.path_role] || s.path_role || 'Stage',
    roleKey: s.path_role || 'unknown',
    evidenceState: EVIDENCE_STATE_LABELS[s.source_evidence_state] || s.source_evidence_state || 'Not assessed',
    runtimeAssessment: s.runtime_assessment || 'not_assessed',
    findingCount: (s.finding_refs || []).length,
    probeCount: (s.unknown_probe_refs || []).length,
    anchorStatus: anchorStatus(s),
  }));
  const edges = [];
  for (let i = 0; i < nodes.length - 1; i++) edges.push({ from: nodes[i].stageIndex, to: nodes[i + 1].stageIndex });
  return { nodes, edges };
}

/**
 * Human-readable stage label: prefer the stage's own name prettified, fall back
 * to its role label. Never just the raw snake_case id.
 */
function stageLabel(s) {
  if (s && s.stage && /^[a-z0-9_-]+$/.test(s.stage)) {
    return s.stage
      .split(/[-_]/)
      .filter(Boolean)
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
  }
  return (s && s.stage) || PATH_ROLE_LABELS[(s && s.path_role)] || 'Stage';
}

/**
 * Resolve the reading thesis for a route (what this route explains). Uses
 * profile-authored copy when available; otherwise synthesizes an honest,
 * generic-but-meaningful line from the route family + stage roles (NOT a bare
 * field restatement).
 */
function routeThesis(route, stages) {
  if (route && ROUTE_THESES[route.route_id]) return ROUTE_THESES[route.route_id];
  const roles = [...new Set((stages || []).map(s => PATH_ROLE_LABELS[s.path_role] || s.path_role).filter(Boolean))];
  if (roles.length) {
    return 'This route traces a ' + roles.join(' -> ') + ' path through the system. Each stage is ' +
      'source-visible where anchored; runtime/build/test confidence is recorded per stage.';
  }
  return 'This route traces an ordered system path. Open the diagram to see its stages and where confidence stops.';
}

/**
 * Classify a stage's anchor quality for honest rendering.
 *
 * Priority:
 *  1. If the row carries an export-time-enriched `anchor_status`, trust it
 *     (adapter resolved the file precisely).
 *  2. `line_start > 0` -> 'precise' (a real line anchor exists).
 *  3. `line_start === 0` + a quality note mentioning ambiguity -> 'ambiguous'.
 *  4. `line_start === 0` + a quality note mentioning a missing anchor -> 'missing'.
 *  5. Otherwise 'unresolved' (we simply cannot tell).
 *
 * This NEVER fabricates a precise anchor: a 0/0 line range is never rendered as
 * a precise line number, even if source_excerpt somehow appears.
 */
function anchorStatus(stage) {
  if (stage && stage.anchor_status) return stage.anchor_status;
  const ls = Number(stage && stage.line_start);
  const le = Number(stage && stage.line_end);
  // A precise anchor requires BOTH bounds > 0 (1-indexed range). A row with
  // line_start 0 but line_end 42 is nonsensical and must not be 'precise'.
  if (ls > 0 && le > 0) return 'precise';
  const note = String((stage && stage.route_quality_note) || '').toLowerCase();
  if (note.includes('ambig')) return 'ambiguous';
  if (note.includes('not found') || note.includes('missing') || note.includes('no anchor')) return 'missing';
  return 'unresolved';
}

/**
 * Plain-language explanation for an anchor status. Used in the dossier so a
 * missing/ambiguous anchor is explained in words, not hidden in a badge, and a
 * precise anchor is shown with its snippet.
 *
 * @returns {string|null} null when a snippet should be shown instead (precise)
 */
function anchorExplanation(stage) {
  const status = anchorStatus(stage);
  switch (status) {
    case 'precise':
      return null; // a snippet is shown instead
    case 'ambiguous':
      return 'Ambiguous anchor: the source location could not be pinned to a single line, so no precise line range is shown. The stage is still source-visible at the path above.';
    case 'missing':
      return 'Anchor not found: the referenced source location could not be resolved. The stage is kept visible so the gap is honest, not hidden.';
    case 'missing-file':
      return 'Missing source file: the referenced path does not exist in the target. The stage is kept visible so the gap is honest, not hidden.';
    default:
      return 'Unresolved anchor: no precise source location is available. The stage is kept visible; treat its source path as a pointer, not a verified location.';
  }
}

// ---------------------------------------------------------------------------
// Coverage regions
// ---------------------------------------------------------------------------

/**
 * Bucket the coverage matrix into reading regions. Derives central/peripheral
 * from whether a subject carries any route coverage (central) or not
 * (peripheral). Returns counts + representative subjects for each region so the
 * coverage surface shows scale, not a flat subject table.
 */
function coverageRegions(cm) {
  const covered = [];     // route_status complete
  const partial = [];     // route_status partial
  const routeless = [];   // no meaningful route (route_status missing/not_assessed/blocked)
  const missing = [];     // promotion_state missing / not_assessed (CROSS-CUTTING lens)
  // The primary route buckets (covered/partial/routeless) are mutually exclusive
  // and exhaustive: every subject lands in EXACTLY one, so their counts sum to
  // total. `missing` is a SEPARATE promotion lens — a subject can be `missing`
  // (promotion) AND e.g. `routeless` (route_status); it is reported as its own
  // axis, never added into the primary partition, so the counts never imply
  // missing+covered+... = total.
  for (const c of cm) {
    const rs = c.route_status || 'not_assessed';
    if (c.promotion_state === 'missing' || c.promotion_state === 'not_assessed') missing.push(c);
    if (rs === 'complete') covered.push(c);
    else if (rs === 'partial') partial.push(c);
    else routeless.push(c);
  }
  // central = has any route ref; peripheral = no route ref at all.
  const central = cm.filter(c => c.route_refs && c.route_refs.length);
  const peripheral = cm.filter(c => !(c.route_refs && c.route_refs.length));
  return {
    covered, partial, routeless, missing, central, peripheral,
    counts: {
      total: cm.length,
      covered: covered.length,
      partial: partial.length,
      routeless: routeless.length,
      missing: missing.length,
      central: central.length,
      peripheral: peripheral.length,
    },
  };
}

// ---------------------------------------------------------------------------
// Top probes + findings + handoff
// ---------------------------------------------------------------------------

/**
 * Pick the top N probes for the first screen. Priority: blocked before
 * not_assessed (blocked is the stronger "we tried and could not"), then by
 * probe_risk (medium/high first — these are the ones an admiral cares about),
 * preserving stable order otherwise.
 */
function topProbes(probes, n) {
  const riskRank = { high: 0, medium: 1, low: 2 };
  const stateRank = { blocked: 0, failed: 1, cannot_verify: 2, not_assessed: 3, unknown: 4 };
  // NOTE: rank 0 is a real priority ('blocked', 'high'); use nullish checks,
  // never `|| 9`, which would coerce 0 to 9 and invert the priority.
  const r = (map, v) => (v in map ? map[v] : 9);
  return [...(probes || [])]
    .sort((a, b) => {
      const s = r(stateRank, a.state) - r(stateRank, b.state);
      if (s) return s;
      return r(riskRank, a.probe_risk) - r(riskRank, b.probe_risk);
    })
    .slice(0, n || 3);
}

/**
 * Pick the top N findings for the first screen. Priority: severity (critical ->
 * major -> minor -> info), preserving stable order.
 */
function topFindings(findings, n) {
  const sevRank = { critical: 0, major: 1, minor: 2, info: 3 };
  const r = (v) => (v in sevRank ? sevRank[v] : 9);
  return [...(findings || [])]
    .sort((a, b) => r(a.severity) - r(b.severity))
    .slice(0, n || 3);
}

/**
 * Build the agent-handoff query list (doc 15 §10). Each entry has a stable id,
 * a label, and the concrete command a follow-up agent would run via the query
 * surface. These are generated from the real artifact set (real route ids,
 * receipt target) so they are runnable, not placeholder text.
 */
function handoffQueries(navAtlas) {
  const ni = (navAtlas && navAtlas.navigationIndex) || [];
  const rv = (navAtlas && navAtlas.receiptValidation) || {};
  const routeIds = [...new Set(ni.map(s => s.route_id))];
  const packageRoute = routeIds.find(r => r.includes('package')) || routeIds[0] || '';
  const target = rv.target_id || '';
  const q = (id, label, command) => ({ id, label, command });
  return [
    q('handoff:list-routes', 'List journeys / routes',
      'node portolan-core/scripts/query-atlas-navigation.mjs --bundle <bundle> list-routes'),
    q('handoff:open-package-route', 'Open the package-distribution route',
      packageRoute
        ? 'node portolan-core/scripts/query-atlas-navigation.mjs --bundle <bundle> route --id ' + packageRoute
        : 'node portolan-core/scripts/query-atlas-navigation.mjs --bundle <bundle> list-routes'),
    q('handoff:list-probes', 'List unknown probes',
      'node portolan-core/scripts/query-atlas-navigation.mjs --bundle <bundle> list-probes'),
    q('handoff:list-findings', 'List findings for the package route',
      packageRoute
        ? 'node portolan-core/scripts/query-atlas-navigation.mjs --bundle <bundle> route --id ' + packageRoute
        : 'node portolan-core/scripts/query-atlas-navigation.mjs --bundle <bundle> list-findings'),
    q('handoff:receipt', 'Show receipt validation',
      'node portolan-core/scripts/query-atlas-navigation.mjs --bundle <bundle> receipt'),
    q('handoff:coverage-gaps', 'Show coverage gaps',
      'node portolan-core/scripts/query-atlas-navigation.mjs --bundle <bundle> coverage'),
  ].map(x => ({ ...x, target }));
}

module.exports = {
  buildJourneys,
  buildRouteDiagram,
  routeThesis,
  stageLabel,
  stageRole: (s) => PATH_ROLE_LABELS[(s && s.path_role)] || (s && s.path_role) || 'Stage',
  anchorStatus,
  anchorExplanation,
  coverageRegions,
  topProbes,
  topFindings,
  handoffQueries,
  EVIDENCE_STATE_LABELS,
  PATH_ROLE_LABELS,
};
